name: Weblate

on:
  push:
    branches:
      - 2-3-stable

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - env:
          TOKEN: ${{ secrets.WEBLATE_KEY }}
        run: "curl -F file=@po/blueman.pot -F method=source -H \"Authorization: Token $TOKEN\" https://hosted.weblate.org/api/translations/blueman/2-3/en/file/"
